name: krishix
description: KrishiX - Trusted rural agriculture marketplace for Indian farmers.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/final_krishix_logo2.png
    - assets/images/login_bottom.png
    - assets/images/KrishiX.svg
    - assets/images/splash.jpg
    - assets/images/tractor.jpeg
    - assets/images/machin.jpeg
    - assets/images/seed.jpeg
    - assets/images/pets.jpeg
    - assets/images/land.jpeg
    - assets/images/services.jpeg
    - assets/images/fruits.jpeg
    - assets/images/all.jpg
    - assets/images/Banner.jpeg
    - assets/images/seed.jpg
    - assets/images/food.jpeg
   